### ISSUE TITLE
Handlebars helper not correctly loaded when Verticals are used

### ISSUE THREAD

**Issue by Nathaire** [microsoft-search/pnp-modern-search#1092]
**Version used**
Ex: 4.2.3

**Describe the bug**
Using a custom Handlerbars helper within PnP Results WebPart (not configured to used input query _Default value_) and PnP Results WebPart is part of a PnP Vertical, the following error is display: **Error: Missing helper: "stringMatch"**

**To Reproduce**
1. Create a new Modern Site Page
2. Add PnP Search Box
3. Add PnP Vertical (configure 2 of them)
4. Add 2 PnP Search Results (Details List)
5. Link each the PnP Search Result WebPart to a separate Vertical
6. In the first PnP Search Results
   1. Configure extensibility libraries to use manifest ID '5e1c605c-e978-42ec-b7d1-3bae19595ab5'
![image](https://user-images.githubusercontent.com/8290006/122755944-02de9100-d296-11eb-8dcb-ed1bb436c973.png)
   2. Configure Title column Handlebars template to use the new helper stringMatch, i.e.
![image](https://user-images.githubusercontent.com/8290006/122756029-27d30400-d296-11eb-92cd-89f3c998e7e9.png)
7. Publish the page
8. Load the page in a new Tab, force refresh to be sure no cache is here
9. Type * in the PnP Search box and press _Enter_
10. The results are displaying an error:
![image](https://user-images.githubusercontent.com/8290006/122756271-7a142500-d296-11eb-99bb-1a454ac077e2.png)

**Expected behavior**
Handlebars helpers are loaded correctly even when verticals are used.

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome (not tested on others)

**Additional context**
If the same page is edited again and in the PnP Search WebPart, the input query is configured to have a default value, i.e. * then everything works correctly:
![image](https://user-images.githubusercontent.com/8290006/122756501-c8292880-d296-11eb-9243-889f2f86645f.png)
![image](https://user-images.githubusercontent.com/8290006/122756541-d24b2700-d296-11eb-83a5-262919cc7a65.png)

When needed, I can share my SPFx package in PM and give access to my Dev Tenant where two pages are created, one with the problem and the other one without (having the default query input value set). Here below all exported configuration of the WebParts:
[webpartproperties.zip](https://github.com/microsoft-search/pnp-modern-search/files/6686379/webpartproperties.zip)

**Comment by wobba** [comment]
Is your setup the minimal setup for repro? And it's probably related to a similar issue I fixed regarding helpers and filter web part.

**Comment by Nathaire** [comment]
Yes, I think it's the minimal setup to repro, without vertical it works like a charm (it took me a while to find out repro steps :-)). I'm not sure it has to do with the Filter WebPart as this one is not used in my scenario. Adding the extension to both Results WebPart did not solve the issue

**Comment by wobba** [comment]
So the issue is two result parts, where extension is regged in one... and with two vertical wp's? Two result wp's where you reg in one works fine?

**Comment by Nathaire** [comment]
Only one Vertical WebPart is added but this one contains 2 Verticals (see image in description). Vertical 1 is linked to Results WebPart 1 (which is configured with the extension) and Vertical 2 to the other Results WebPart 😊

**Comment by wobba** [comment]
Should be fixed with #1098 now in the dev branch.
