### ISSUE TITLE
Results shown when search box is empty

### ISSUE THREAD

**Issue by abhitalks** [microsoft-search/pnp-modern-search#1721]
**Version used**
4.5.3

**Describe the bug**
The search results should be empty with no results when no search term has been entered in the search box. E.g. an empty search box at page load. This is happening even when "`Use a default value`" is unchecked. According to documentation: "_Optionaly, you can set a default query text when there is no value for the connected source (ex: an empty search box at page load)_". 

Still every time user goes to the search page, they are greeted with random search results.

**To Reproduce**
1. Go to search results web parts settings
2. On connections tab connect to search box, and leave the "`Use a default value`" checkbox unchecked
3. Publish the page
4. Browse to the search page to see search results without entering anything in search box.

**Expected behavior**
On page load when a user visits the search page, the search box is empty and so the search results should also be empty.

**Screenshots**
![pnp-srch-default](https://user-images.githubusercontent.com/15690125/149624877-a535ada2-98b4-4ab4-abc4-1e6ec879c11c.png)

**Desktop (please complete the following information):**
 - Browser Chrome, Edge

**Additional context**
Upgraded from v4.1 was the last change.

**Comment by wobba** [comment]
From the image above seems you have not picked a value in the "PnP - Search Box's properties"

Works as expected on my end.
![image](https://user-images.githubusercontent.com/51104/149800005-c9be7e07-c8b0-47f0-b56a-c004c9035244.png)

**Comment by abhitalks** [comment]
> From the image above seems you have not picked a value in the "PnP - Search Box's properties"
> 
> Works as expected on my end. ![image](https://user-images.githubusercontent.com/51104/149800005-c9be7e07-c8b0-47f0-b56a-c004c9035244.png)

Thanks @wobba, but I have selected "_Search Query_" option. I did try selecting it with mouse and keyboard both. It shows as selected when returning to it later. When I change the "_Connect to Source_" to something else like "_Page Environment_" and related properties, it works. But the moment I set source as "_Search Box_" and select "_Search Query_", it reverts back to showing results as shown in the screenshot above.

Do you need me to share a screen recording with you?

**Comment by wobba** [comment]
@abhitalks I cannot repro. Do you have `{searchTerms}` in the query template field?

**Comment by till-llit** [comment]
we have 2 tenants - i can reproduce this behaviour only in one of them

in our test tenant (targeted release) i get results with empty query from PNP Modern Search Result Webpart.

with 100% identical configuration i receive no results in our Productive Tenant (standard release).

@abhitalks : do you have targeted release (user or tenant) enabled in your setup?

**Comment by abhitalks** [comment]
> @abhitalks I cannot repro. Do you have `{searchTerms}` in the query template field?

@wobba Yes. Here is the value that I have in my "_query template_" field: `{searchTerms} -path:https://tenant-my.sharepoint.com`.

It was working fine before, and sadly I really don't know when exactly it stopped working and what triggered it. I came to realize only after users started complaining earlier this month. I thought maybe v4.1 needed to be upgraded and so I did that and upgraded to v4.5.3. But, it still doesn't work.

**Comment by abhitalks** [comment]
> @abhitalks : do you have targeted release (user or tenant) enabled in your setup?

Yes we have "_targeted release_" enabled at tenant level.

**Comment by wobba** [comment]
@abhitalks I still cannot repro. Using the same query template as you have and this search box config.

![image](https://user-images.githubusercontent.com/51104/149993950-c1dc8c5d-7ff4-4686-8988-6f70ba6a22fc.png)

**Comment by wobba** [comment]
That helps and I can repro.. and it is correct. The correct query template should be:

`{?{searchTerms} -path:https://techmikael-my.sharepoint.com}`

except that fails as well. Agree that the above template should work @FranckyC? Similar to classic.  If `{searchTerms}` is empty, then remove the full template.

**Comment by FranckyC** [comment]
Could be fixed by this PR https://github.com/microsoft-search/pnp-modern-search/pull/1692. Can you try with the current `develop` branch?

**Comment by till-llit** [comment]
is there a sppkg available for the develop branch? i do not have a build environment available

**Comment by abhitalks** [comment]
> That helps and I can repro.. and it is correct. The correct query template should be:
> 
> `{?{searchTerms} -path:https://tenant-my.sharepoint.com}`
> 
> except that fails as well. Agree that the above template should work @FranckyC? Similar to classic. If `{searchTerms}` is empty, then remove the full template.

It doesn't work even if I remove the OneDrive exclusion and simply use `{searchTerms}` on its own. 

BTW: How is `{inputQueryText}` token different from `{searchTerms}`?

**Comment by wobba** [comment]
if you have {searchTerms} only it should work - unless you have a result source with a filter as well. Your short term workaround is to keep {searchTerms} as the template in the web part and create a result source with `{?{searchTerms} -path:https://tenant-my.sharepoint.com}` in it, and reference that result source.

`inputQueryText` is a web part specific token, `searchTerms` can be evaluated on the server when using the SharePoint provider.

**Comment by FranckyC** [comment]
> inputQueryText is a web part specific token, searchTerms can be evaluated on the server when using the SharePoint provider.

That's right and I changed to this behavior recently in the `develop` branch so you may not have the latest version here. That could explain.

**Comment by wobba** [comment]
@FranckyC I now see the full template `{?{searchTerms} -path:https://tenant-my.sharepoint.com}` is passed along the query 🙂 If you build the dev branch it should fix your issue @abhitalks.

**Comment by FranckyC** [comment]
Will be resolved in the upcoming 4.5.4 version.

**Comment by fug4zi** [comment]
Configured today and i have the same issue with version 4.5.4

Tried these
```
{?{searchTerms} -path:https://tenant-my.sharepoint.com}
{?{searchTerms} path:https://tenant-my.sharepoint.com}
{searchTerms}
```

**Comment by abhitalks** [comment]
@FranckyC and @wobba, the issue persists in v4.5.4 irrespective of `{?{searchTerms} -path:https://tenant-my.sharepoint.com}` or just `{searchTerms}`.

When the search box is empty, the results are still shown.

**Comment by Hickey77** [comment]
Any updates on this issue?  Was able to work around with default value of ""

**Comment by wobba** [comment]
@stevebeauge they seem to be the same yes. And I don't have an update.

**Comment by Hickey77** [comment]
Thanks guys.  Trying to use this to solve a big problem with Viva Connections for a large customer (Lack of SPO search in some Viva C clients)

**Comment by tmccart1** [comment]
Has this been fixed yet?  I am also seeing search results on page load even though I have the correct syntax in the query template field.

`{?{searchTerms} -path:https://tenant-my.sharepoint.com}`

**Comment by wobba** [comment]
It's an API issue, not web part issue. Feel free to log a support case with Microsoft to push this.

**Comment by heinrich-ulbricht** [comment]
We are currently struggling with search results being shown for an empty search box when using the "Microsoft Search" source (not SharePoint Search). Which source is this issue about?

**Comment by wobba** [comment]
Change the query template to `{?{searchTerms}}`. Then you get 0 when the search term is empty.

**Comment by wobba** [comment]
@heinrich-ulbricht what does the query (JSON) look like with the Graph source? An empty query string? Could be that we need to add logic in the web part to not make an API query if it's empty.

**Comment by heinrich-ulbricht** [comment]
@wobba I currently don't have access to the affected site but will hopefully be able to check back when I do have it again. But that was my guess also; that the API handles an empty query like "*" and the web part would have to take care of this.

**Comment by wobba** [comment]
@FranckyC Seems like for an empty query and the use of template `{?{searchTerms} -path:https://tenant-my.sharepoint.com}` we pass down `{? -path:https://tenant-my.sharepoint.com}`.

Seem we should add a check in TokenService that if a token which works behind the scenes is empty, we should not remove it and pass it down to the service. That or add logic to honor `{?..}` notation.

**Comment by Lisa-G531** [comment]
I'm having the same issue.
Results are show on page load and while the Search Box is empty.
PnP Search Version 4.2.3
Works fine in UAT and Test but not in Prod.



![PnP Search V4 - Bug](https://user-images.githubusercontent.com/75793144/201357195-40c6aab1-a6cd-4679-bca7-7b76fc75f5e1.png)

**Comment by wobba** [comment]
This is actually an API issue where an empty query sent is now returned as a * query, and we will try to fix it in the web part itself when connected to a search box.

**Comment by silersbald** [comment]
I was also having results show on page load in version 4.8.  After reading this thread I was able to fix it by using `{?{searchTerms} Path:{Site} }` for the query template  and checking the "Use a default value" box.  I left the Default value field empty.

**Comment by thatcow** [comment]
> I was also having results show on page load in version 4.8. After reading this thread I was able to fix it by using `{?{searchTerms} Path:{Site} }` for the query template and checking the "Use a default value" box. I left the Default value field empty.

Thanks for this. It works for me as well.

**Comment by till-llit** [comment]
@sharepointnewbie is there a space between "path:" and the url? it should read

`path:https://company.sharepoint.com/sites/Technical/shared%20documents/products`

without a searchterm this query will always return all results from the given site collection.

to avoid this i would advise to create a search result source with the path included in the query and use this result source for your search results webpart.

**Comment by sharepointnewbie** [comment]
> @sharepointnewbie is there a space between "path:" and the url? it should read
> 
> `path:https://company.sharepoint.com/sites/Technical/shared%20documents/products`
> 
> without a searchterm this query will always return all results from the given site collection.
> 
> to avoid this i would advise to create a search result source with the path included in the query and use this result source for your search results webpart.

@till-llit 
thanks for the reply. Sorry no space, that was a typo
- {searchTerms} path:https://company.sharepoint.com/sites/Technical/shared%20documents/products
returns results from correct path, but displays ALL documents in result BEFORE anything is entered in search. 
Other than that, the search works as desired, its just a little confusing for users.
-{searchTerms}
returns results from entire site collection, but displays NO results until a search is entered. I realise this is expected, I only mention as it is clear the addition of the path create the issues with empty search showing all results.

I would like to see result from ONLY the path mentioned, but see no results until a search term is entered (the same way it behaves with the default query of {searchTerms}

I cannot find how to create a search result source as you suggest.

**Comment by till-llit** [comment]
you can create a result source either tenant wide in the sharepoint admin or on a site collection level.

if you are site collection admin you can go to site settings -> search result source to create one:

https://company.sharepoint.com/sites/Technical/_layouts/15/manageresultsources.aspx?level=sitecol
or whatever your Search Site Collection is where you use the pnp search webparts.

afterwards you need to scope the search result webpart to utilize this search result source in the webpart settings.

**Comment by pquinn1212** [comment]
Hi All, 

Just out of curiosity did this get fixed atall ? i am on version 4.8.0 and had this issue come up this morning. It was working fine yesterday then all off a sudden the search results has information in.
<img width="632" alt="image" src="https://user-images.githubusercontent.com/1913918/227496594-84c6a197-1000-4b39-87d4-910e5837946b.png">
I am using the default Wikiscope which was fine last night. My query template is just {searchTerms} i have also tried {?{searchTerms}} but still the same, the only thing i did yesterday was reindex the database and also create a new query scope ?

Thanks

**Comment by sam888k12** [comment]
For anyone still having trouble, double check your syntax.  I was confused by this {?{searchTerms}} and put the path:tenantURL after the second } like this: {?{searchTerms}} path:https://company.sharepoint.com/sites/Technical/shared%20documents/products  

When I fixed it to {?{searchTerms} path:https://company.sharepoint.com/sites/Technical/shared%20documents/products} it worked and the search results was empty if the search box has not been populated.

**Comment by wobba** [comment]
Made a fix for `{?{searchTerms}}` notation when searchTerms is empty in #3028

**Comment by apathak95** [comment]
@wobba I am still facing the same issue. We have updated the webpart to latest version Version: 4.16.0.Still getting the random results on blank search query. I am using {?{SearchTerm}} with the result source guid to get the results form that specific source .

<img width="258" alt="Image" src="https://github.com/user-attachments/assets/2cfdf8cf-2dfd-4b4b-9fae-8813608ead93" />

**Comment by stevebeauge** [comment]
> [@wobba](https://github.com/wobba) I am still facing the same issue. We have updated the webpart to latest version Version: 4.16.0.Still getting the random results on blank search query. I am using {?{SearchTerm}} with the result source guid to get the results form that specific source .
> <img alt="Image" width="258" src="https://private-user-images.githubusercontent.com/101961912/433705721-2cfdf8cf-2dfd-4b4b-9fae-8813608ead93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ3MDY0NjgsIm5iZiI6MTc0NDcwNjE2OCwicGF0aCI6Ii8xMDE5NjE5MTIvNDMzNzA1NzIxLTJjZmRmOGNmLTJkZmQtNGI0Yi05ZmFlLTg4MTM2MDhlYWQ5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQxNVQwODM2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGZkYjQyNGMwODEwMTk2ODBmZTJjNWQ4NmY0NGFmMGY4ZTc2ODc2MTM3MWNmZDY4MTNmZWQ0Y2YxOWI4ZDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gU0QRetgOpKWuD5FG3zgqrtv28KOo1IuK43fatAznTU">

@apathak95 What's the point of encapsulating your query with `{?...}`. Seems useless for me. 
That said, search api has sometimes weird behavior. In order to distinguish if pnp search is guilty, can you check the network query and show us which query is actually sent ? You can search the network query with /postquery

**Comment by apathak95** [comment]
@stevebeauge we do not want to send the query at inital page load , we need to send the query when we click the  search button of search box. BTW i check the network logs and search postquery, it did call the search api with the seach term blank(which we don't want) on inital load.

**Comment by kasperbolarsen** [comment]
In that case your query is most likely wrong.  The {?} Approach is normally used to ensure an initial load when searchTerms is empty.
Can you share the query.?

**Comment by rvanandel-hcg** [comment]
@kasperbolarsen, I work with @apathak95 and we've been troubleshooting this for a few days now. We've tried a number of things but so far nothing is working. Right now our Query template is set to {searchTerms} and have a defined result source. The search webpart is working properly when we enter text in the search box on the same page but when we first load the page, the search web part is passing a query to querypost. There's got to be a way to prevent this from happening. Our users are going to be very confused on why search results are returned before they enter a search query.

{
    "__metadata": {
        "type": "Microsoft.Office.Server.Search.REST.SearchRequest"
    },
    "ClientType": "PnPModernSearch",
    "Properties": {
        "results": [
            {
                "Name": "EnableDynamicGroups",
                "Value": {
                    "BoolVal": true,
                    "QueryPropertyValueTypeIndex": 3
                }
            },
            {
                "Name": "EnableMultiGeoSearch",
                "Value": {
                    "BoolVal": true,
                    "QueryPropertyValueTypeIndex": 3
                }
            },
            {
                "Name": "ClientFunction",
                "Value": {
                    "StrVal": "PnPSearchWebPart",
                    "QueryPropertyValueTypeIndex": 1
                }
            },
            {
                "Name": "ListId",
                "Value": {
                    "StrVal": "66dc08ad-cc84-4f18-a90f-0924f0ae7247",
                    "QueryPropertyValueTypeIndex": 1
                }
            },
            {
                "Name": "ListItemId",
                "Value": {
                    "StrVal": "38",
                    "QueryPropertyValueTypeIndex": 1
                }
            }
        ]
    },
    "Querytext": "",
    "EnableQueryRules": false,
    "QueryTemplate": "{searchTerms}",
    "SourceId": "4580938c-dd9e-4959-a095-4b9bee712cec",
    "EnableNicknames": false,
    "EnablePhonetic": false,
    "Culture": 1033,
    "TimeZoneId": 13,
    "Refiners": "RefinableString29(filter=10/0/*,sort=frequency/ascending,deephits=1000000),RefinableString76(filter=10/0/*,sort=name/ascending,deephits=1000000),RefinableString79(filter=10/0/*,sort=name/ascending,deephits=1000000),RefinableDate00(discretize=manual/2024-04-15T19:22:28.565Z/2025-01-15T20:22:28.565Z/2025-03-15T19:22:28.565Z/2025-04-08T19:22:28.565Z/2025-04-14T19:22:28.566Z/2025-04-15T19:23:28.566Z)",
    "RefinementFilters": {
        "results": []
    },
    "RowLimit": 15,
    "StartRow": 0,
    "TrimDuplicates": true,
    "SortList": {
        "results": [
            {
                "Property": "LastModifiedTime",
                "Direction": 0
            }
        ]
    },
    "SelectProperties": {
        "results": [
            "LastModifiedTime",
            "FolderType",
            "ModifiedById",
            "Title",
            "Path",
            "PictureThumbNailURL",
            "HitHighlightedSummary",
            "FileType",
            "IsDocument",
            "FileExtension",
            "contentClass",
            "Rank",
            "SPSiteURL",
            "ParentLink",
            "FileName",
            "FolderPath",
            "ListItemID",
            "ListUrl",
            "ContentType",
            "SPContentType",
            "ContentTypeID",
            "RefinableString76",
            "RefinableString77",
            "RefinableString78",
            "RefinableString79",
            "RefinableString80",
            "RefinableString81",
            "RefinableString82",
            "RefinableString3",
            "RefinableString84",
            "RefinableString86",
            "RefinableString87",
            "RefinableString90",
            "RefinableString12",
            "RefinableDate00",
            "RefinableDate01"
        ]
    },
    "HitHighlightedProperties": {
        "results": []
    },
    "ReorderingRules": {
        "results": []
    }
}

**Comment by kasperbolarsen** [comment]
Resently we have seen a number of cases where the old approach of defining a custom search result source have caused issues. 
I will recommend trying to switch to using the LocalSharePointResults and update the Query Template in the Results web part accordingly

**Comment by rvanandel-hcg** [comment]
I changed the result source to LocalSharePointResults and updated the Query Template to the following. It had no affect. 

{searchTerms} (ContentType:"Workday Project Document" Or ContentType:"Workday Project")

**Comment by kasperbolarsen** [comment]
Try

({searchTerms} AND (ContentType:"Workday Project Document" Or ContentType:"Workday Project"))

I assume you haven't set the default value for the search box to * on page 3 in the Results web part?

**Comment by rvanandel-hcg** [comment]
Updating the query template had no affect. We have "Use a default value" unchecked.

Use input query text: On with Dynamic Value selected
Connect to Source: PnP - Search Box
PnP - Search Box's Properties: Search query

Still, when the page first loads, we're getting search results back.

**Comment by kasperbolarsen** [comment]
What does the resulting query in the network tab looks like?

**Comment by rvanandel-hcg** [comment]
I'm not sure why that's relevant. We don't want a query sent in the first place.  Below is the payload sent when the page first loads. 

{
    "__metadata": {
        "type": "Microsoft.Office.Server.Search.REST.SearchRequest"
    },
    "ClientType": "PnPModernSearch",
    "Properties": {
        "results": [
            {
                "Name": "EnableDynamicGroups",
                "Value": {
                    "BoolVal": true,
                    "QueryPropertyValueTypeIndex": 3
                }
            },
            {
                "Name": "EnableMultiGeoSearch",
                "Value": {
                    "BoolVal": true,
                    "QueryPropertyValueTypeIndex": 3
                }
            },
            {
                "Name": "ClientFunction",
                "Value": {
                    "StrVal": "PnPSearchWebPart",
                    "QueryPropertyValueTypeIndex": 1
                }
            },
            {
                "Name": "ListId",
                "Value": {
                    "StrVal": "66dc08ad-cc84-4f18-a90f-0924f0ae7247",
                    "QueryPropertyValueTypeIndex": 1
                }
            },
            {
                "Name": "ListItemId",
                "Value": {
                    "StrVal": "38",
                    "QueryPropertyValueTypeIndex": 1
                }
            }
        ]
    },
    "Querytext": "",
    "EnableQueryRules": false,
    "QueryTemplate": "{searchTerms} And (ContentType:\"Workday Project Document\" Or ContentType:\"Workday Project\")",
    "SourceId": "8413cd39-2156-4e00-b54d-11efd9abdb89",
    "EnableNicknames": false,
    "EnablePhonetic": false,
    "Culture": 1033,
    "TimeZoneId": 13,
    "Refiners": "RefinableString29(filter=10/0/*,sort=frequency/ascending,deephits=1000000),RefinableString76(filter=10/0/*,sort=name/ascending,deephits=1000000),RefinableString79(filter=10/0/*,sort=name/ascending,deephits=1000000),RefinableDate00(discretize=manual/2024-04-15T21:42:42.129Z/2025-01-15T22:42:42.129Z/2025-03-15T21:42:42.129Z/2025-04-08T21:42:42.129Z/2025-04-14T21:42:42.130Z/2025-04-15T21:43:42.130Z)",
    "RefinementFilters": {
        "results": []
    },
    "RowLimit": 15,
    "StartRow": 0,
    "TrimDuplicates": true,
    "SortList": {
        "results": [
            {
                "Property": "LastModifiedTime",
                "Direction": 0
            }
        ]
    },
    "SelectProperties": {
        "results": [
            "LastModifiedTime",
            "FolderType",
            "ModifiedById",
            "Title",
            "Path",
            "PictureThumbNailURL",
            "HitHighlightedSummary",
            "FileType",
            "IsDocument",
            "FileExtension",
            "contentClass",
            "Rank",
            "SPSiteURL",
            "ParentLink",
            "FileName",
            "FolderPath",
            "ListItemID",
            "ListUrl",
            "ContentType",
            "SPContentType",
            "ContentTypeID",
            "RefinableString76",
            "RefinableString77",
            "RefinableString78",
            "RefinableString79",
            "RefinableString80",
            "RefinableString81",
            "RefinableString82",
            "RefinableString3",
            "RefinableString84",
            "RefinableString86",
            "RefinableString87",
            "RefinableString90",
            "RefinableString12",
            "RefinableDate00",
            "RefinableDate01"
        ]
    },
    "HitHighlightedProperties": {
        "results": []
    },
    "ReorderingRules": {
        "results": []
    }
}

**Comment by rvanandel-hcg** [comment]
We're still looking for a solution to this issue. I did find that if I set the query Template box to read {searchTerms} and remove the other parts, the webpart will not display search results. However, I need to target this for a couple of content types. If I put the following in the query template, the search results web part will display results even if I didn't enter anything in the Search Box.

{searchTerms}  And (ContentType:"Workday Project Document" Or ContentType:"Workday Project")

The same is true if I set Result Source Id / Scope|Name to use a defined search source with the same query as above and set Query template to {searchTerms}. 

Since this is a closed issue, I will open a new one with this specific bug.
