### ISSUE TITLE
PnP Modern Search V4 - Query Template Path:{\Site.URL}/<LibraryName> not working

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#1769]
v4.5.3

### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/1767

<div type='discussions-op-text'>

<sup>Originally posted by **jameelrrs** January 28, 2022</sup>
Hi,

To start with,  **PnP Modern Search WebPart is a great Solution**.  Amazing and appreciate the work done by the community.

What was working:
     Using a dynamic token in the PnP - Search Results **query template** to point my results to a specific library, since we have multiple sites as below:
    ` Path:{\Site.URL}/<LibraryName>`

Issue:
This was working fine until we planned to move to V4.  However the same query doesn't work in version V4.  Somehow, it adds \" in the beginning or ending of the queryModifier and adding LIbraryName after it doesn't give results.

Is there something missing.  Please suggest...  Thanks in advance.</div>

**Comment by wobba** [comment]
@FranckyC `path:{\Site}/lala` is being sent as `path:{Site}/lala`, meaning the `\` is stripped on the request.

**Comment by FranckyC** [comment]
Yes I noticed that, you can use the Path:{site.absoluteUrl} token as a workaround for now. It should work.

**Comment by FranckyC** [comment]
@wobba  @jameelrrs should be fixed in #1769.

**Comment by MaruVC** [comment]
Hi. I am trying to point a search to a specific folder, quite new to all this and don't really know how to put it together. 
If i try Path:"SiteURL" it works for the entire site, but if i try Path:"LibraryURL" it does not work.
I tried as mentioned above Path:{SiteURL}/LibraryName and other combinations of that sort but still shows 0.
what will be the proper way to write this please?
thanks
