### ISSUE TITLE
Refinement does not filter results when on a result page greater than one

### ISSUE THREAD

**Issue by quarterhorse** [microsoft-search/pnp-modern-search#332]
**Version used**
3.13.0 - May 2020

**Describe the bug**
When applying refinement based on a refinable string associated with a crawled property for taxonomy field only on page 1 of the results filtering is applied.  If on another page and a value is selected, no filtering is applied.

**To Reproduce**
1 - Issue a query resulting in multiple pages of results.
2 - Click on result page 3
3 - Select one value in the refinement panel to filter against a taxonomy field value
4 - The result set is not filtered
5 - Click on page 1 and the results are now filtered

**Expected behavior**
Clicking on a refinement value should apply filtering regardless of the current page

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

**Comment by RamaKaryam** [comment]
We have the same problem. It used to work with separate pagination webpart.

**Comment by wobba** [comment]
Agree. Applying a filter should reset to page 1 with that filter applied.

**Comment by jindalv10** [comment]
@quarterhorse : I have fixed this issue. You can add following screenshot code in SearchResultsContainer.tsx file

![image](https://user-images.githubusercontent.com/13974138/85887829-78fd0480-b7b6-11ea-8232-43ef59db67b8.png)

**Comment by wobba** [comment]
@jindalv10 you should do a PR 🙂

**Comment by Jeroen00** [comment]
When can we expect the fix for this issue to be released?

**Comment by wobba** [comment]
@Jeroen00 can you re-check with v3.14.2 as I think the fix was included there.

**Comment by Jeroen00** [comment]
> @Jeroen00 can you re-check with v3.14.2 as I think the fix was included there.

I just tested 3.14.2 but unfortunately the issue still exists. I get search results with paging; I go to page 2 and filter/refine on a property but the results are not filtered and I remain on page 2. When I go back to page 1 the filter is also not applied, only works if I apply the filter when I already am on page 1.

**Comment by wobba** [comment]
Fixed by #361
