### ISSUE TITLE
Search box WebPart has stopped working after 23rd Jun 2020 - "Querytext":"*"

### ISSUE THREAD

**Issue by Sachindagar** [microsoft-search/pnp-modern-search#347]
**Version used**
Ex: 3.7

**Describe the bug**
I think MS has done some changes in the Search API due to that the search box WebPart has stopped working. They are pushing the changes tenant wise hence it is impacting the tenant which has deployed the latest patch.

**To Reproduce**
1) Add Search box web-part and search web-part
2) Try to search anything by typing any keyword in search box, the results are not refined.

**Expected behavior**
Keyword search should be working.

**Desktop (please complete the following information):**
 - IE11, Chrome, Mozilla Firefox 

**Additional context**
When we trying to search anything from the keyword search, the results are not refined based on the keyword. We have checked the request payload and found that the keyword provided in the searchbox is converted to "". Hence the final Querytext":"".

Below is the payload

{"request":{"__metadata":{"type":"Microsoft.Office.Server.Search.REST.SearchRequest"},"ClientType":"ContentSearchRegular","Properties":{"results":[{"Name":"EnableDynamicGroups","Value":{"BoolVal":true,"QueryPropertyValueTypeIndex":3}},{"Name":"EnableMultiGeoSearch","Value":{"BoolVal":true,"QueryPropertyValueTypeIndex":3}}]},**"Querytext":"*",**"EnableQueryRules":false,"QueryTemplate":"{searchTerms}","RowLimit":10,"SelectProperties":{"results":["Title","Path","Created","Filename","SiteLogo","PreviewUrl","PictureThumbnailURL","ServerRedirectedPreviewURL","ServerRedirectedURL","HitHighlightedSummary","FileType","contentclass","ServerRedirectedEmbedURL","DefaultEncodingURL","owstaxidmetadataalltagsinfo","Author","AuthorOWSUSER","SPSiteUrl","SiteTitle","IsContainer","IsListItem","HtmlFileType","UniqueID"]},"TrimDuplicates":false,"SortList":{"results":[{"Property":"Created","Direction":0},{"Property":"Size","Direction":1}]},"Refiners":"","HitHighlightedProperties":{"results":[]},"RefinementFilters":{"results":[]},"ReorderingRules":{"results":[]}}}

Also, This is the advisory message posted to the SharePoint health - I think there is some bug introduced
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
User profile changes not reflected in search results within SharePoint Online
SP217039, SharePoint Online, Last updated: June 25, 2020 3:34 AM
**Start time: June 23, 2020 5:24 PM**
Status
Service degradation
User impact
User profile changes may not be reflected in search results within SharePoint Online.
Are you experiencing this issue?
Is this post helpful?
Latest message View history
Title: User profile changes not reflected in search results within SharePoint Online

User Impact: User profile changes may not be reflected in search results within SharePoint Online.

More info: Affected users can reach out to support to temporarily mitigate this issue through a manual re-crawl; however, changes made after the re-crawl will remain impacted.

Current status: We've developed a fix for the issue and are deploying it to the affected environments. Once the deployment completes, we’ll run a joblet to fully mitigate the issue. We anticipate the full mitigation will take approximately five days to complete.

Scope of impact: Any user may be impacted by this issue.

Root cause: A recent code change to the SharePoint Online service inadvertently resulted in impact.

Next update by: Friday, June 26, 2020, 5:30 AM (6/25/2020, 7:30 PM UTC)

**Comment by kachihro** [comment]
Lots of other issues - currently being investigated/fixed - refer to #325

**Comment by kachihro** [comment]
This issue as you described is working for me - prior to update/fix.    
* Added Search (Input) WebPart
* Added Search RESULTS WebPart
* Click Configure 
* Click the [...] and Connect To Source
* Search Box -> Search Query
* Publish Page

Search is working - and returning results - according to the Search Query.

(*** This is a tenant that is having the same issues as describved in #325)

**Comment by Sachindagar** [comment]
Yes, @kachihro , we are also getting the issue mentioned in #325 and this is the new issue.

**Comment by Sachindagar** [comment]
> This issue as you described is working for me - prior to update/fix.
> 
> * Added Search (Input) WebPart
> * Added Search RESULTS WebPart
> * Click Configure
> * Click the [...] and Connect To Source
> * Search Box -> Search Query
> * Publish Page
> 
> Search is working - and returning results - according to the Search Query.
> 
> (*** This is a tenant that is having the same issues as describved in #325)

Yes, that was working fine us as well till last night in one of the tenant but today it's not working

**Comment by Sachindagar** [comment]
During debug, it is identified that 'this._searchQuery' is coming as undefined.

**Comment by Sachindagar** [comment]
Getting undefined for **this._searchQuery**

/**
   * Handler used to notify data source subscribers when the input query is updated
   */
  private _onSearch = (searchQuery: ISearchQuery): void => {

    this._searchQuery = searchQuery;
    this.context.dynamicDataSourceManager.notifyPropertyChanged('searchQuery');
  }

**Comment by kachihro** [comment]
Thanks - I've made some changes in line with #325 - which should fix this issue also

**Comment by Sachindagar** [comment]
Can you please advise where you have made the changes?

**Comment by kachihro** [comment]
This is a link to the PR - and the files changed.    Mainly within the SearchBoxWebPart - and the SearchResultsWebPart
https://github.com/microsoft-search/pnp-modern-search/pull/348/files

**Comment by wobba** [comment]
Please log the issue at https://github.com/SharePoint/sp-dev-docs/issues as it relates to dynamic data and page environment, not these specific web parts. @kachihro you need to resolve your PR as it targeted the wrong branch.

**Comment by rudfoss** [comment]
We are seeing the same problem. Thansk for looking into it. Just upgraded to v3.13 and the issue persists. I've made a small gif on how to reproduce it, but I guess you guys are already on it.
![search-box-connection-problem](https://user-images.githubusercontent.com/1716298/85720118-6b7d4700-b6f0-11ea-8e7a-2509c37b838e.gif)

**Comment by wobba** [comment]
Tracked in #325 and https://github.com/SharePoint/sp-dev-docs/issues/5947
