### ISSUE TITLE
PnP Modern Search Web parts on home page break modern search page controls

### ISSUE THREAD

**Issue by lekhav19** [microsoft-search/pnp-modern-search#537]
**Version used**
3.15.3

The "Exit Search" button on out of box modern search results page on site doesn't work when PnP Modern Search Web parts are used on home page.

1. Add Search Box or Search results webparts on home page and configure it
2. Click on modern search bar on top of the page
3. Once the search results page loads, click on "Exit Search"
4. The URL changes but user remains on the search results page
5. If the issue doesn't occur at the first attempt, please try it again

**Expected behavior**
Clicking on "Exit Search" should take the user back to home page.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, Edge]

**Additional context**
If we refresh the Search results page, and then click on "exit search" it works as expected and takes the user to homepage.

**Comment by cpluceDev** [comment]
yes. i was just about to post this. i have a critical business requirement to use both searches and i just discovered this week this same issue

**Comment by cpluceDev** [comment]
![image](https://user-images.githubusercontent.com/25770942/98563971-68cf5880-2271-11eb-90e4-4274689a19ba.png)

**Comment by cpluceDev** [comment]
we have our search box on just any site page. when we search the  from the modern web part than go and search the Microsoft search the results load but exit search link wont work and parts of page freezes. looks like modern search web parts are conflicting with the Microsoft search. looks like it may be caching issue

**Comment by cpluceDev** [comment]
wonder if there is something we can do to clear the cached artifacts when leaving the page

**Comment by cpluceDev** [comment]
i get this when clicking on the verticals from the OOTB MSFT(Modern) search 
![image](https://user-images.githubusercontent.com/25770942/98571127-d54e5580-2279-11eb-8dec-25b77a127f63.png)

**Comment by wobba** [comment]
Should be fixed in the dev branch. I'll close the issue when we do a new v3 release.

**Comment by waynel2** [comment]
@wobba - any idea when the new v3 release will be?  We have a new system launch scheduled for 25 Nov hence we're keen to see if we can resolve this prior else we'll have to revert to using the classic search experience.  Thanks

**Comment by FranckyC** [comment]
@waynel2 is the new 3.16.0 version resolve your issue?

**Comment by Tareqe** [comment]
Any idea when/how this issue can be resolved? 

This is issue is not resolved with new 3.16.0 version. When I click 'Exit search' link below error popup on the browser console. 

![image](https://user-images.githubusercontent.com/77013188/103664892-c49c2200-4f40-11eb-9fec-0e7d2a701b38.png)

**Comment by lekhav19** [comment]
Agree with @Tareqe issue isn’t resolved yet with version 3.16

**Comment by wobba** [comment]
Here's a video of v3.16 - and I cannot repro. No errors in the console.

https://user-images.githubusercontent.com/51104/103764465-ce468800-501b-11eb-9c63-20a5e657a846.mp4

**Comment by lekhav19** [comment]
That is correct. I retried and it works as expected. this is now fixed for me.
