### ISSUE TITLE
using PnP Search with Query Suggestion On -  getting 403 error when calling the Search API

### ISSUE THREAD

**Issue by hsamdani12** [microsoft-search/pnp-modern-search#581]
I'm logged in as a user with Site Collection Admin as well as SharePoint Tenant Admin permission.

I'm getting 403 error when calling the Search API 

https://tenant/sites/search-site/_api/search/suggest

{"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}

Also is there a way to get the search box web part code only extracted to a seperate sppkg, the given solution combines all the search webparts. I would like to get VS Code solution with only search box web part.

**Comment by wobba** [comment]
@hsamdani12 as for a one web part package, you have to do a custom build, and not something we will do.

Does the suggest API work via the SP search query tool if you connect to the same site? And, permission denied is an auth problem, not the web parts itself.

![image](https://user-images.githubusercontent.com/51104/100460237-26a67380-30c7-11eb-8a9d-852d594b770b.png)

**Comment by hsamdani12** [comment]
@wobba  

Thanks, It does work using the tool. I see HTTP 200 for status, and response in Raw tab. 
But when I try directly from the site I'm getting 403 error.

Error making HttpClient request in queryable [403] ::> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}

**Comment by wobba** [comment]
Can you compare the requests, and verify they are called at the same tenant/site url? And most likely you're not getting what you want due to the way suggestions are scoped per site collection.

**Comment by hsamdani12** [comment]
Thanks. I’ll check on it.  What we are trying to achieve is like an suite bar (OOTB) Search Box behaviour.  So we want a PnP Search Box (as a React component) wrapped inside an App Customizer deployed at the hub level, so the search should be scoped to hub and all the associated hub site. We wanted same suggestion\ type ahead behaviour as it is in the suite bar search box.

**Comment by wobba** [comment]
Why not scope the oob suitbar searchbox to hub scope and use that one? And if you need custom results, use the search box with the PnP part.

**Comment by hsamdani12** [comment]
We need additional customization, adding and advance search filters with multiple metadata to be filtered on. So it will another custom advance search component next to it and pass KQL search string to the search box. This search box need to have the OOTB search suggestion behaviour. We are hiding the suite bar search box and want to have one in the header section (using app customizer). Similar to this - https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/js-application-intranet-searchbox <https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/js-application-intranet-searchbox>

**Comment by wobba** [comment]
@hsamdani12 The suggestions you see in the suitbar search box is a lot more than what the SP REST suggestions API gives you, and there is no public API exposing this today.

The search suggestions (common search queries) logic in SP requires recording of clicked results which happens today on OOB search pages. The PnP web parts has not implemented this. And as I mentioned it's recorded per site collection, meaning each site collection will get different suggestions based on usage.

With all the logic you need you might be better off building a custom search box.

**Comment by hsamdani12** [comment]
Ok thanks, that is what we are doing, building a custom search box. I was wondering if you have any documentation about the the suite bar suggestion search box behaviour ? 
Also to be sure SP REST suggestion API used by PnP Search box only support static search, based on pre-configured values.

**Comment by wobba** [comment]
@hsamdani12 the suite bar search box support redirect to another page, and rewrite of the query before passing it to a web part via dynamic data.

**Comment by hsamdani12** [comment]
@wobba  thanks. We are looking into using OOTB search box. But we want the OOTB search box to be in the "Top" placeholder besides our custom search components we create and put in the top placeholder using SPFx extension. 
We can move it down the suite bar to Top placeholder using some DOM manipulation, but was wondering if there is a better approach. 

I was also hoping Microsoft has the public API for the suite bar search box! that way we don't have to do all this and can consume in our custom search box.

**Comment by wobba** [comment]
The only supported operation with the suite bar search box is to intercept the query, and possibly modify it, before you consume it via dynamic data in a web part.

If I understand correctly what you want is to get global suggestions, but only query suggestions (not files and sites). There were plans to allow custom suggestions using SPFx, but the work has been paused afaik.

**Comment by hsamdani12** [comment]
Hi,

Yes that first point would not help meet our requirement.

We have a Hub Site where we deployed the custom search box along with a custom advance search filler control to pass KQL queries to search result page along with content in custom search box.
These controls have been put in the Tope Placeholder.
We hide the suite bar search box.
All we want is OOTB Suggestion (Files and Sites within the Hub - OOTB behaviour in our own custom search box). As you mentioned that API is not publicly available to consume  ? Am I correct ?

**Comment by wobba** [comment]
Correct. The only API at the moment is the one you got 403 error on - which I cannot repro, so you have to compare requests and figure out what the difference is from the query tool vs the one made by the web part.

**Comment by hsamdani12** [comment]
Ok thanks for confirming.
Also I'm not going down that rabbit hole as  that is the PnP Search Suggestions which I supports static suggestions(upload a txt file to search schema), that is not what we need.

**Comment by wobba** [comment]
@hsamdani12 you can look into creating a custom suggestion provider - which is supported in the PnP v4 search box. https://microsoft-search.github.io/pnp-modern-search/extensibility/ Still don't help to get the OOB functionality though.
