### ISSUE TITLE
Access denied on PDF if permissions are ""Restricted View"

### ISSUE THREAD

**Issue by SPT-Seb** [microsoft-search/pnp-modern-search#646]
**Version used**
Ex: 3.15.3.0

**Describe the bug**
When user has "View Only" permissions on webpart PDF results, when clicking on PDF results, users land on Access Denied page.

**To Reproduce**
Set up a document library with a group "TEST users" having only "View only" permission. Put your test user into this group.
Add PDF and wait for crawler to do its job.
Log in with your test user.
Search your PDF, click on it -> Access denied.

**Expected behavior**
Open PDF in Office Web Apps

**Screenshots**
N/A

**Desktop (please complete the following information):**
Edger Chromium

**Additional context**
Note that other modern Microsoft WebPart have the same behaviour, but not all of them (no problem of course if you try to open the PDF directly from document library.
Issue seems to come from "{{getUrl item}}" returns url like :
https://<domain>.sharepoint.com/sites/<sitecoll>/<doclib>/<filename>.pdf which, when user has ViewOnly permissions, leads to Access Denied error.
URL as https://<domain>.sharepoint.com/sites/<sitecoll>/<doclib>/Forms/AllItems.aspx?id=%2Fsites%2F<sitecoll>%2F<doclib>%2F<encodedfilename>%2Epdf works.

**Comment by wobba** [comment]
v3.16 which should append `?web=1` to the click Url. Does that solve it?

**Comment by SPT-Seb** [comment]
Thank you Mikael for your answer.
"?web=1" doesn't solve the issue (tested on 2 different tenants just in case)
After further investigation, I confirm that Classical OOTB experience (/_layouts/15/osssearchresults.aspx ) and Modern OOTB experience (/_layouts/15/search.aspx) have also the same issue. So IMO too, it's not PnP job to fix this. 
I think you can close the ticket but just in case: do you know where is the best place to request a fix to MS about such issue?

**Comment by wobba** [comment]
😁 I would be the one. I'll set up an internal repro and log it. Not sure if there's an easy fix though as from a search perspective we don't really know anything beside that the user has read access to the document.

Does sharing links from a document library work for user with View only? Trying to see if it makes more sense to engage with the SharePoint team for a solution. Ideally `<URL>?web=1` should work for all web scenarios, as it adds less logic on clients wanting to point to a preview.

**Comment by SPT-Seb** [comment]
Exciting!
Additional info after investigation : 
PDF results from : 
- "Highlighted content"
- "Recent documents"
- "Document library"
Fail also.
On "File viewer" webpart. PDF appears then flip to an error inviting user to download file, which fails (because user doesn't have proper permissions for download).

Regarding "Sharing link" option, if a user, having normal access to a PDF file, share a link using "People with existing access" option with someone having "View only" permission, you will have an access denied error message also. URL is https://domain.sharepoint.com/:b:/r/sites/site/doclib/folder/filename.pdf?csf=1&web=1&e=6letters.

Issue is only for PDF files and it seems to come from that search engine gives "old school" sharepoint links (https://domain.sharepoint.com/sites/site/doclib/folder/filename.pdf?web=1) which are then redirected to URL like https://domain.sharepoint.com/sites/site/doclib/Forms/AllItems.aspx?id=encoded_path. It may be in that very redirection step that an Access Denied exception occurs.
Do not hesitate if you have other questions!

**Comment by wobba** [comment]
I assume it happens for any non-office file... say a .txt file for example as well.

**Comment by wobba** [comment]
@SPT-Seb Can you share the exact permission scope you set up?

**Comment by SPT-Seb** [comment]
I confirm for non Office files : Access Denied on .TXT and .MSG
But pictures (.JPG) are OK.
Regarding permissions, I tested using "Restricted view". I recreated a custom permission level  (with "View item" and no "Open Item") and now it works BUT you can DL the PDF if web=1 is missing ...
I will rest a bit and recreate a collection for testing in English (mine is in French) so I can share screen shots.

**Comment by wobba** [comment]
Some image formats are handled by the SPO cache for image caching - it's not an easy thing to create the best click url for all item types. That said, we're working thru this for Microsoft Search internally as well, so any change will benefit PnP Modern Search and be implemented here.

I've raised the read-only issue with the SharePoint PG and awaiting their input.

**Comment by SPT-Seb** [comment]
**Update** (a bit long, but I try to be complete) :
There are 3 permission levels to know : 
- "Read" the classical one which allow end users to download files, open them in Office Web Apps and Office Client (and PDF are open in Edge or OWA)
- "View Only" this permission level is created by activating "SharePoint Enterprise" site coll feature. It's like read without "Open Item" right. It's supposed to prevent download of files which can be seen in OWA.
- "Restricted View" this permissions level is not available at site level. It appears in doc libs after you share a file using "specific person" blocking download. According to the description, it should be very similar to "view only".
Both "View Only" and "Restricted View" have a wrong behaviour with PDFs.

**Reproductions steps :**
- Create a Team site
- Add a test user "A" in "Visitors" group and test user "B" in "Members group
- On "Documents" library, break permissions inheritance and set "View only" to visitors ("A" user) and "Restricted view" to user "B"
- Upload various files with different extensions including PDFs
- Go grab a cup of coffe while crawler does its job.
- play with web parts, search results and URLs with PDFs

**Expected Behavior:**
User A and user B should be able to read PDF using OWA AND not be able to download it, whatever the way you try to access the PDF.

**Observed Behavior:**
For user A ("View Only" permission): files are indexed and appears with preview in search results, "Highlighted content" WP and "Recent documents" WP.
No problem (view through OWA and no download) opening Word, TXT, MSG, PDF files from doc lib or WebParts or through modern search (/_layouts/15/search.aspx). 
Except you can dowload pictures (.JPG) if you use "Highlighted content" WP.
BUT, if you try the direct URL (https://domain.sharepoint.com/sites/site/doclib/folder/filename.pdf, which you can get at the bottom of details pane or if you are not a noob in SP) to .TXT, .MSG or .PDF file, file is directly dowloaded/displayed in Edge. **-> Security issue**
-> expected behavior : Access denied as it does for Office files.

For user B ("Restricted View" permission): files are indexed and appears with preview in search results, "Highlighted content" WP and "Recent documents" WP.
- OK for Office files
- Direct URLs and Access denied on .PNG, TXT, .MSG, and .PDF files using "Highlighted content" WP and "Recent documents" WP and Modern search (/_layouts/15/search.aspx) results. 
Adding a ?web=1 doesn't solve the issue.
Considering the "exotic" origin of "Restricted View" permission, I guess it's not a big deal and "View only" should be the one used. Even if you can easily mix both of them (especially in French). This what I did when  I created this thread : I was using "Restricted View" instead of "View Only". I noticed it when you asked me to give detailed permissions.

**Comment by SPT-Seb** [comment]
Regarding PnP modern search, adding "web=1" in version 3.16 may hide the "view only" issue but there is an issue on SPO side IMO.

**Comment by wobba** [comment]
@SPT-Seb thank you for the writeup, and will report back on our internal findings.

**Comment by wobba** [comment]
The issue has been fixed somewhat, but closing as it's not a search issue but a SharePoint issue.

**Comment by EliezerBee** [comment]
> @SPT-Seb thank you for the writeup, and will report back on our internal findings.

Any updates on this?

**Comment by droper-lcb** [comment]
Hi @wobba, I notice this access denied issue also occurs when trying to open the PreviewURL if the user only has item level permissions and no (default) read permissions at the library level (Both in PNP Search and SP OOTB Search). 

But interestingly if you access the preview option from the context menu in the library itself, it works, so there seems to be some extra step or reference that the preview button in the library does that doesn't occur when you access the previewURL directly. The resulting URL (after double decoding) is exactly the same, so there is some trick here that accessing from the library does that search doesn't.

Currently I have to use the direct file path with the hope that PDFs are set to open in browser on the client in order to get the 'pnp-filepreview' working, which isn't ideal, and likely will break if we ever want to restrict users from downloading.

**Comment by wobba** [comment]
Thumbnail != preview on hover - so different API calls :)

**Comment by exar10** [comment]
Any progress on this? This is still an issue with Restricted View/Limited Access users not being able to view PDFs (and presumably other non-Microsoft files) in browser.

**Comment by kasperbolarsen** [comment]
No, absolutely no progress on this as the case was closed 3 years ago.
If you have any additional findings and have checked that it works in classic search or MS search,  then please open a new issue and reference this issue
