### ISSUE TITLE
Thumbnails are empty

### ISSUE THREAD

**Issue by JBestebreurtje** [microsoft-search/pnp-modern-search#69]
**Version used**
Modern Search - December 2019

**Describe the bug**
Thumbnails are empty

I want to use the PNP webpart to search through a large Picture gallery.
I'm also having the issue that thumbnails are empty. Also the Tiles view not showing pictures.

2nd issue is when you click on a picture the PNP webpart links to the following link which gives you en empty page. See screenshot
/sites/027314/Shared%20Documents/Forms/DispForm.aspx?ID=9

Standard SharePoint search redirects you to the following link: Then it works!

**Desktop (please complete the following information):**
 - Browser [Chrome]

/sites/027314/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2F027314%2FShared%20Documents%2FPR%20foto%2Ejpg&parent=%2Fsites%2F027314%2FShared%20Documents

**Screenshots**

![image](https://user-images.githubusercontent.com/50945662/72901150-80ad0e80-3d29-11ea-8fce-d8301bf9701f.png)

![image](https://user-images.githubusercontent.com/50945662/72901298-cc5fb800-3d29-11ea-814f-565de665c5d0.png)

**Comment by FranckyC** [comment]
Hi @JBestebreurtje . This should be resolved by #74. Feel free to test it out before release.

**Comment by JBestebreurtje** [comment]
Thanks you very much. I don't have the correct tools in place to create the new sppkg file. Is it possible if you can provide me the sppkg file so I can test it!

That would be very helpful

**Comment by FranckyC** [comment]
@JBestebreurtje  Here you go https://github.com/microsoft-search/pnp-modern-search/releases/download/3.9.0/pnp-modern-search-parts.sppkg

**Comment by JBestebreurtje** [comment]
Hi Francky,

Thanks for this,
I've installed the update but unfortunately I still don't see thumbnails and cannot open the jpg or png pictures.

![image](https://user-images.githubusercontent.com/50945662/73351006-68d80c00-428e-11ea-9f38-59dc376bee77.png)

**Comment by FranckyC** [comment]
Is is the same with the 'Simple List' layout? You could update the query to target only jpg or png files and see what happens. Also make sure the latest version is used in this page and not the previous.

**Comment by JBestebreurtje** [comment]
Yes, also the “Simple list” view is not showing thumbnails and the 3.9 version is installed correctly.

Do you want to do a check on my pc?

Kind regards | Met vriendelijke groet,

Jeroen Bestebreurtje | Functioneel Applicatie Beheerder | Royal BAM Group nv

Runnenburg 9, 3981 AZ Bunnik | P.O. Box 20, 3980 CA Bunnik, The Netherlands
T +31 650655293 | M +31 650655293 | E jeroen.bestebreurtje@bam.com<mailto:jeroen.bestebreurtje@bam.com> | W www.bam.com<http://www.bam.com>
Trade register 30058019 | Statutory office in Bunnik, The Netherlands
[cid:image001.jpg@01D5D6BE.2CE568A0]
Van: Franck Cornu <notifications@github.com>
Verzonden: woensdag 29 januari 2020 12:19
Aan: microsoft-search/pnp-modern-search <pnp-modern-search@noreply.github.com>
CC: Bestebreurtje, Jeroen <jeroen.bestebreurtje@bam.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [microsoft-search/pnp-modern-search] Thumbnails are empty (#69)


Is is the same with the 'Simple List' layout? You could update the query to target only jpg or png files and see what happens. Also make sure the latest version is used in this page and not the previous.

**Comment by FranckyC** [comment]
Weird. Where are stored your images? A modern document library?

**Comment by JBestebreurtje** [comment]
Yes it's a modern doc lib. 
Only thing I did is adding the ContentType picture to the library and add some metadata.
I've now change some pictures back to CT document, maybe that has any effect?

![image](https://user-images.githubusercontent.com/50945662/73429969-2cafb480-433d-11ea-9051-d5cc19c5d776.png)
